name: get_env_info
description: GetArch infrastructure package, get app environment information
version: 0.6.2
repository: https://github.com/Hu-Wentao/get_env_info

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_arch_core: '>=0.6.1 <2.0.0'
#  get_arch_quick_start: ^0.6.1
#  get_arch_quick_start:
#    path: D:/flutter_arch/get_arch_quick_start
  injectable: ^0.4.0+1
  json_serializable: ^3.3.0
  freezed_annotation: ^0.11.0
  package_info: ^0.4.1
  device_info: ^0.4.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.11.4
  injectable_generator: ^0.4.1

flutter:
